import { FileText } from "lucide-react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { fetchLatestExecutiveSummary } from "../../api/executiveSummary";
import { Card, ConfidenceBadge, EmptyState, ErrorState, LoadingState, PageHeader } from "../../components";
import { formatDateTime } from "../../lib/format";
import { CustomerHealthBanner } from "./CustomerHealthBanner";
import { ExecutiveSummarySection } from "./ExecutiveSummarySection";
import { KeyMetricsSection } from "./KeyMetricsSection";
import { BusinessDriversSection } from "./BusinessDriversSection";
import { SentimentEmotionIntentSection } from "./SentimentEmotionIntentSection";
import { LeadershipPrioritiesSection } from "./LeadershipPrioritiesSection";
import { RecommendedActionsSection } from "./RecommendedActionsSection";
import { AiInvestigationSection } from "./AiInvestigationSection";
import { CustomerEvidenceSection } from "./CustomerEvidenceSection";

export default function ExecutiveBrief() {
  const { data, isLoading, isError, error, refetch } = useQuery({
    queryKey: ["executive-summary", "latest"],
    queryFn: fetchLatestExecutiveSummary,
  });

  const latest = data?.latest;

  return (
    <div>
      <PageHeader
        title="Executive Brief"
        subtitle="AI-generated Voice of Customer summary for leadership."
        actions={
          <Link
            to="/feedback-explorer"
            className="rounded-md bg-teal-800 px-3 py-2 text-sm font-medium text-white hover:bg-teal-900"
          >
             Open Feedback Explorer
          </Link>
        }
      />

      {isLoading && <LoadingState label="Loading the latest executive brief…" />}

      {isError && (
        <ErrorState
          description={
            error instanceof Error
              ? error.message
              : "Could not reach the InsightCX backend."
          }
          onRetry={() => refetch()}
        />
      )}

      {!isLoading && !isError && !latest && (
        <Card>
          <EmptyState
            icon={<FileText className="h-8 w-8" aria-hidden="true" />}
            title="No executive summary has been generated yet"
            description="Generate the first executive summary from Administration to see the Customer Health status, business drivers, and recommended actions here."
            action={
              <Link
                to="/administration"
                className="rounded-md bg-teal-800 px-3 py-2 text-sm font-medium text-white hover:bg-teal-900"
              >
                Go to Administration
              </Link>
            }
          />
        </Card>
      )}

      {!isLoading && !isError && latest && (
        <div className="space-y-8">
          <div className="flex flex-wrap items-center gap-x-6 gap-y-1 text-sm text-slate-500">
            <span>
              Generated{" "}
              <span className="font-medium text-slate-700">
                {formatDateTime(latest.generated_at)}
              </span>
            </span>
            <span>
              Responses{" "}
              <span className="font-medium text-slate-700">
                {latest.summary.key_metrics.feedback_count.toLocaleString()}
              </span>
            </span>
            <ConfidenceBadge level={latest.summary.confidence.level} />
          </div>

          <CustomerHealthBanner
            health={latest.summary.customer_health}
            businessImpact={latest.summary.business_impact}
          />

          <ExecutiveSummarySection
            summary={latest.summary.executive_summary}
            focus={latest.summary.executive_focus}
            priorityCounts={data.priority_counts}
          />

          <KeyMetricsSection current={latest.summary} previous={data.previous?.summary} />

          <BusinessDriversSection
            drivers={latest.summary.top_business_drivers}
            totalFeedback={latest.summary.key_metrics.feedback_count}
          />

          <SentimentEmotionIntentSection
            sentiment={latest.summary.sentiment_summary}
            emotions={latest.summary.emotion_summary}
            intent={latest.summary.intent_summary}
          />

          <LeadershipPrioritiesSection priorities={latest.summary.leadership_priorities} />

          <RecommendedActionsSection actions={latest.summary.recommended_actions} />

          <AiInvestigationSection
            findings={latest.summary.ai_root_cause_analysis}
            signals={latest.summary.emerging_business_signals}
          />

          <CustomerEvidenceSection verbatims={latest.summary.customer_verbatims} />

          <p className="border-t border-slate-200 pt-4 text-center text-xs text-slate-400">
            Brief generated by InsightCX from{" "}
            {latest.summary.key_metrics.feedback_count.toLocaleString()} customer comments.
          </p>
        </div>
      )}
    </div>
  );
}
